/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package janken;

import java.io.*;

public class Main {

    public static void main(String[] args) {
        Player user = new Player();
        Player computer = new Player();
        Game game = new Game();
        
        
        System.out.println("1.グー");
        System.out.println("2.チョキ");
        System.out.println("3.パー");
        System.out.print("あなたの手を選択してください。>");
        
        String inputNum = "";
        
        try {
            BufferedReader br = new BufferedReader(new InputStreamReader( System.in ) );
            inputNum = br.readLine();
        } catch(IOException e) {
            System.out.println("システムエラー");
            System.exit(0);
        }
        
        if(inputNum.equals("1")) {
            user.setHand(new Gu());
        } else if(inputNum.equals("2")) {
            user.setHand(new Choki());
        } else if(inputNum.equals("3")) {
            user.setHand(new Pa());
        } else {
            System.out.println("1-3を入力してください。");
            System.exit(0);
        }
        
        computer.setRandomHand();
        
        int result = game.judge(user, computer);
        
        String resultStr = "";
        
        if(result == 0) {
            resultStr = "あいこ";
        } else if(result == 1) {
            resultStr = "あなたの勝ち";
        } else if(result == -1) {
            resultStr = "あなたの負け";
        }
        System.out.println("-----対戦結果-----");
        System.out.println("あなたの手:" + user.getHand().getHandName());
        System.out.println("相手の手:" + computer.getHand().getHandName());
        System.out.println("結果:" + resultStr);
        
    }
}
